import '../assets/css/base.css';
import '../assets/css/affiliates.css';
import { header, footer, reveal } from './components.js';
import { affiliates } from './data.js';

const tiles = affiliates.map(({ title, text, href, image, alt }) => `<a class="affiliate-tile" href="${href}" target="_blank" rel="noopener noreferrer sponsored"><span class="affiliate-tile__image"><img src="${image}" alt="${alt}" loading="lazy"></span><span class="affiliate-tile__content"><strong>${title}</strong><small>${text}</small></span></a>`).join('');
document.querySelector('#app').innerHTML = `<div class="ember-field" aria-hidden="true"></div>${header(false)}<main class="page-shell"><section class="profile-card" data-animate="rise"><div class="banner-wrap"><img class="banner" src="/uploads/banner.jfif" alt="Jason Shadow affiliate banner"><div class="banner-overlay"></div></div><div class="profile-content"><img class="avatar" src="/uploads/profile.png" alt="Profile photo of Jason Shadow"><p class="eyebrow">Official affiliate hub</p><h1>Jason Shadow</h1><p class="tagline">Everything you need to Heal in one place.</p><section class="affiliate-gallery" aria-label="Affiliate partner gallery">${tiles}</section><nav class="link-list secondary-links" aria-label="Additional links"><a class="link-button instagram" href="https://www.instagram.com/jason.shadow_official/" target="_blank" rel="noopener noreferrer"><span class="icon" aria-hidden="true">◎</span><span><strong>Instagram</strong><small>@jason.shadow_official</small></span></a><a class="link-button" href="/"><span class="icon" aria-hidden="true">⌂</span><span><strong>Official Website</strong><small>jason-shadow.com</small></span></a><button class="link-button donate" type="button" data-paypal-open><span class="icon" aria-hidden="true">♥</span><span><strong>Support &amp; Donate</strong><small>PayPal donation</small></span></button></nav></div></section></main>${footer()}`;
document.querySelector('[data-paypal-open]').addEventListener('click', () => window.open('https://www.paypal.com/donate/?hosted_button_id=6XPT97RRUBEA6', 'paypal-donate', 'popup=yes,width=520,height=720,noopener,noreferrer'));
reveal();
