import '../assets/css/base.css';
import '../assets/css/home.css';
import { header, footer } from './components.js';
import { services, portfolio, fallbackNews } from './data.js';
import { client, loadNews } from '../lib/appwrite.js';

const cards = portfolio.map(([title, text, file], index) => `<article class="portfolio-preview-card${index === 0 ? ' is-active' : ''}" data-portfolio-card data-title-key="portfolioItem${index + 1}Title" data-text-key="portfolioItem${index + 1}Text"><div class="portfolio-media"><video class="portfolio-video" controls preload="metadata" aria-label="${title}"><source src="/uploads/portfolio/${file}.mp4" type="video/mp4"></video><picture><img src="/uploads/portfolio/${file}.png" alt="${title}" loading="lazy" onerror="this.hidden=true"></picture><span class="media-fallback">Upload: uploads/portfolio/${file}.png or ${file}.mp4</span></div><h3 data-i18n="portfolioItem${index + 1}Title">${title}</h3></article>`).join('');
const renderNews = items => items.map(([dateTime, date, title, text]) => `<article class="news-card"><time datetime="${dateTime}">${date}</time><h3>${title}</h3><p>${text}</p></article>`).join('');

document.querySelector('#app').innerHTML = `<div class="ember-field" aria-hidden="true"></div>${header()}<main id="top">
<section class="hero" data-animate="rise"><div class="banner-wrap"><img class="banner" src="/uploads/banner.jfif" alt="Dark stage banner with microphone and spotlights"><div class="banner-overlay"></div></div><div class="hero-content"><img class="avatar" src="/uploads/profile.png" alt="Profile photo of Jason Shadow"><p class="eyebrow" data-i18n="heroEyebrow">Baritone Singer · Speaker · Host</p><h1>Jason Shadow</h1><p class="tagline" data-i18n="heroTagline">A distinctive voice between goosebumps, storytelling and dark elegance — for music, stages, events, keynotes and brand moments.</p><div class="signature-player"><button class="play-button" type="button" aria-label="Play signature song"><span aria-hidden="true">▶</span></button><div><strong>The Healing Shadow</strong><small>Play-button placeholder · Audio coming soon</small></div></div><div class="hero-actions"><a class="primary-action" href="#booking">Book now</a><a class="secondary-action" href="#portfolio">View portfolio</a><a class="secondary-action" href="https://www.linkedin.com/in/jason-winckler/" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div></section>
<section id="about" class="section about-section about-section-centered" data-animate="rise"><div class="section-heading"><p class="eyebrow">About Me</p><h2>Presentation Video</h2></div><div class="about-video-card"><video class="intro-video" controls preload="metadata" poster="/uploads/profile.png" aria-label="Introduction video"><source src="/uploads/about/introduction.mp4" type="video/mp4"></video><div class="video-placeholder"><span class="play-button" aria-hidden="true">▶</span><strong>Presentation video</strong><small>Upload your MP4 as uploads/about/introduction.mp4</small></div></div></section>
<section id="services" class="section services-section" data-animate="rise"><div class="section-heading"><p class="eyebrow">Services</p><h2>Services</h2><p>A warm baritone voice and confident stage presence for live moments, hosted events and spoken productions.</p></div><div class="service-list service-list-centered">${services.map(([t,d],i)=>`<div><strong data-i18n="${['serviceLiveTitle','serviceHostTitle','serviceProjectTitle'][i]}">${t}</strong><span>${d}</span></div>`).join('')}</div></section>
<section id="portfolio" class="section portfolio-section" data-animate="rise"><div class="section-heading"><p class="eyebrow">Portfolio</p><h2>Portfolio</h2><p>My three biggest projects</p></div><div class="portfolio-stage"><div class="portfolio-track">${cards}</div><div class="portfolio-controls"><button type="button" class="portfolio-arrow" data-portfolio-prev aria-label="Previous portfolio item">‹</button><button type="button" class="portfolio-arrow" data-portfolio-next aria-label="Next portfolio item">›</button></div><div class="portfolio-active-copy" aria-live="polite"><h3 data-portfolio-active-title>KÖPI am Ring Rheine — Singer</h3><p data-portfolio-active-text>This is an example order I had.</p></div></div></section>
<section id="news" class="section" data-animate="rise"><div class="section-heading"><p class="eyebrow">News</p><h2>Latest news</h2><p class="content-status" data-news-status role="status">Loading latest news…</p></div><div class="news-grid" data-news-grid>${renderNews(fallbackNews)}</div></section>
<section id="booking" class="section booking-section" data-animate="rise"><div class="section-heading"><p class="eyebrow">Contact &amp; Booking</p><h2>Request a project</h2><p>Briefly describe your project, choose your budget and Jason will get back to you for the next steps.</p></div><form class="booking-form" action="https://formsubmit.co/business@jason-shadow.com" method="post"><input type="hidden" name="_subject" value="Neue Booking-Anfrage über jason-shadow.com"><label><span>Name</span><input name="Name" autocomplete="name" required></label><label><span>Email</span><input name="E-Mail" type="email" autocomplete="email" required></label><label><span>Project type</span><select name="Projektart" required><option value="">Please select</option><option>Singing / Feature</option><option>Speaker / Hosting</option><option>Speech / Keynote</option><option>Live performance / Event</option><option>Other</option></select></label><label><span>Budget: <output id="budget-output" for="budget">500 €</output></span><input id="budget" name="Budget" type="range" min="150" max="1000" step="50" value="500"></label><label class="full-span"><span>Message</span><textarea name="Nachricht" rows="6" required></textarea></label><button class="primary-action full-span" type="submit">Send request</button></form></section></main>${footer()}`;

import('../script.js');
client.ping().catch(() => {
  console.warn('Appwrite backend ping failed.');
});
loadNews().then(items => { const status = document.querySelector('[data-news-status]'); if (items?.length) { document.querySelector('[data-news-grid]').innerHTML = renderNews(items); status.textContent = `${items.length} news items loaded.`; } else status.textContent = 'Current highlights'; }).catch(() => { document.querySelector('[data-news-status]').textContent = 'Live updates are temporarily unavailable. Showing saved highlights.'; });
